name: Simple Go Build
 
on: workflow-dispatch
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup Go version
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.1'
    - run: go run helloworld.go   
